#!/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH

case "$1" in
    start) ;;
    *) exit 1 ;;
esac

[ -x /usr/bin/xdm ] || exit 0
umask 077
mkdir -p /run/xdm /var/log || exit 1
chown 0:0 /run/xdm || exit 1
chmod 0700 /run/xdm || exit 1
exec /usr/bin/xdm -nodaemon -config /etc/X11/xdm/xdm-config
