#!/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH

case "$1" in
    start) ;;
    *) exit 1 ;;
esac

[ -x /usr/bin/startx ] || exit 0
[ -x /usr/bin/startxfce4 ] || exit 0
[ -x /usr/bin/dbus-run-session ] || exit 0
exec /usr/bin/startx /usr/bin/mos-xfce-session -- vt2 </dev/tty2 >/dev/tty2 2>&1
