#!/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin
case "$1" in
start)
    [ -r /proc/net/dev ] || exit 1
    while IFS= read -r interface; do
        case "$interface" in
            *e01:*) exit 0 ;;
        esac
    done </proc/net/dev
    printf '%s\n' 'e01 is unavailable'
    exit 1
    ;;
stop) : ;;
restart) "$0" stop; "$0" start ;;
esac
