#!/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin
. /etc/init.d/boot-functions

case "$1" in
    3) ;;
    *) exit 1 ;;
esac

for script in /etc/rc3.d/S*; do
    [ -x "$script" ] || continue
    name=${script##*/}
    name=${name#S[0-9][0-9]}
    boot_action "Starting $name" "$script" start
done
