#!/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin
. /etc/init.d/boot-functions

case "$1" in
    3) ;;
    0 | 6)
        printf '%s\n' 'Stopping system processes.'
        /sbin/killall5 -15 || true
        sleep 2
        /sbin/killall5 -9 || true
        sync
        umount -a -r
        mount -n -o remount,ro /
        sync
        case "$1" in
            0) exec /sbin/poweroff -f ;;
            6) exec /sbin/reboot -f ;;
        esac
        ;;
    *) exit 1 ;;
esac

for script in /etc/rc3.d/S*; do
    [ -x "$script" ] || continue
    name=${script##*/}
    name=${name#S[0-9][0-9]}
    boot_action "Starting $name" "$script" start
done
