#!/bin/sh
export PATH=/sbin:/bin:/usr/sbin:/usr/bin
. /etc/init.d/boot-functions

boot_banner
boot_action 'Remounting root filesystem read-write' mount -o remount,rw /
if [ -e /usr/libexec/Xorg.wrap ] || [ -e /usr/bin/sudo ]; then
    boot_action 'Setting privileged system file ownership' /usr/bin/python3 /usr/libexec/mos-system-ownership.py || exit 1
fi
boot_action 'Mounting proc filesystem' mount -t proc proc /proc
boot_action 'Mounting sysfs filesystem' mount -t sysfs sysfs /sys
boot_action 'Mounting pseudo-terminal filesystem' mount -t devpts devpts /dev/pts
boot_action 'Mounting runtime filesystem' mount -t tmpfs tmpfs /run
boot_action 'Mounting shared memory filesystem' mount -t tmpfs tmpfs /dev/shm || exit 1
boot_action 'Setting shared memory permissions' chmod 1777 /dev/shm || exit 1
boot_action 'Removing stale X11 display files' rm -f /tmp/.X0-lock /tmp/.tX0-lock /tmp/.X11-unix/X0 || exit 1
boot_action 'Creating X11 socket directories' mkdir -p /tmp/.X11-unix /tmp/.ICE-unix
boot_action 'Setting X11 socket directory permissions' chmod 1777 /tmp /tmp/.X11-unix /tmp/.ICE-unix
boot_action 'Setting system hostname' hostname "$(cat /etc/hostname)"
