#!/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin
case "$1" in
start)
    /usr/sbin/sshd
    ;;
stop)
    [ -f /var/run/sshd.pid ] && kill "$(cat /var/run/sshd.pid)" 2>/dev/null || true
    ;;
restart) "$0" stop; "$0" start ;;
esac
