# Select panes and windows without the prefix key.
bind -n C-h select-pane -L
bind -n C-j if-shell -F '#{==:#{pane_current_command},fzf}' 'send-keys C-j' 'select-pane -D'
bind -n C-k if-shell -F '#{==:#{pane_current_command},fzf}' 'send-keys C-k' 'select-pane -U'
bind -n C-l select-pane -R
bind -n C-n next-window
bind -n C-p previous-window
bind -n M-l resize-pane -R 10
bind -n M-k resize-pane -U 10
bind -n M-j resize-pane -D 10
bind -n M-h resize-pane -L 10
# Create new windows at the end of the window list.
bind c new-window -a \; move-window -t 99 \; move-window -r
# Exchange the current window with an adjacent window.
bind-key -n C-Right swap-window -t +1\; select-window -t +1
bind-key -n C-Left swap-window -t -1\; select-window -t -1
# Split panes while retaining the current working directory.
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
set -g default-shell /bin/bash
set -g status-bg '#00C000'
set -g status-fg white
set -g window-style 'bg=#404040'
set -g window-active-style 'bg=black'
set -g window-status-separator ''
set -g status-left "#[fg=white,bg=#004000] #{?SSH_CONNECTION,R,L} #[fg=#004000,bg=#00C000]>#[bg=#00C000] "
set -g status-right " #[fg=#008000,bg=#00C000]<#[fg=white,bg=#008000] %Y-%m-%d #[fg=#004000,bg=#008000]<#[fg=white,bg=#004000] %H:%M:%S "
set-window-option -g window-status-current-format '#[fg=#00C000,bg=#00F000]>#[fg=black,bg=#00F000] #{s|.*/([^/]+/[^/]+/[^/]+)$|\1|:pane_current_path} #[fg=#00F000,bg=#00C000]>'
set-window-option -g window-status-format '#[fg=black,bg=#00C000]  #{s|.*/([^/]+/[^/]+/[^/]+)$|\1|:pane_current_path}  '
set-option -g status-interval 1
set -g mouse off

# Render pane borders with ASCII characters.
set -g pane-border-lines simple
