# switch panes using Alt-arrow without prefix
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
label="pstree -s #{client_pid} | grep -iq 'ssh' && echo 'R' || echo 'L'"
bind -n C-h run "tmux select-pane -L"
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l run  "tmux select-pane -R"
bind -n C-n next-window
bind -n C-p previous-window
bind -n M-l resize-pane -R 10
bind -n M-k resize-pane -U 10
bind -n M-j resize-pane -D 10
bind -n M-h resize-pane -L 10
# always create new tab at right most
bind c new-window -a \; move-window -t 99 \; move-window -r
# Move tab to next/previous
bind-key -n C-Right swap-window -t +1\; select-window -t +1
bind-key -n C-Left swap-window -t -1\; select-window -t -1
# Split panes using % and " and keep the current path
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
set -g default-shell /bin/bash
set -g status-bg '#00C000'
set -g status-fg white
set -g window-style 'bg=#404040'
set -g window-active-style 'bg=black'
set -g window-status-separator ''
set -g status-left "#[fg=white,bg=#004000] #(eval $label) #[fg=#004000,bg=#00C000]#[bg=#00C000] "
set -g status-right " #[fg=#008000,bg=#00C000]#[fg=white,bg=#008000] %Y-%m-%d #[fg=#004000,bg=#008000]#[fg=white,bg=#004000] %H:%M:%S "
set-window-option -g window-status-current-format '#[fg=#00C000,bg=#00F000]#[fg=black,bg=#00F000] #(echo "#{pane_current_path}" | rev | cut -d'/' -f-3 | rev) #[fg=#00F000,bg=#00C000]'
set-window-option -g window-status-format '#[fg=black,bg=#00C000]  #(echo "#{pane_current_path}" | rev | cut -d'/' -f-3 | rev)  '
set-option -g status-interval 1
set -g mouse off
