MANDATORY_MANPATH /usr/share/man
MANDATORY_MANPATH /usr/local/share/man
MANPATH_MAP /bin /usr/share/man
MANPATH_MAP /sbin /usr/share/man
MANPATH_MAP /usr/bin /usr/share/man
MANPATH_MAP /usr/sbin /usr/share/man
MANPATH_MAP /usr/local/bin /usr/local/share/man
MANPATH_MAP /usr/local/sbin /usr/local/share/man
MANDB_MAP /usr/share/man /var/cache/man
MANDB_MAP /usr/local/share/man /var/cache/man/local
DEFINE pager /usr/bin/more
DEFINE nroff /usr/bin/nroff -mandoc
DEFINE troff /usr/bin/groff -mandoc
DEFINE eqn /usr/bin/eqn
DEFINE neqn /usr/bin/neqn
DEFINE tbl /usr/bin/tbl
DEFINE col /usr/bin/col
DEFINE compressor /usr/bin/gzip -c7
SECTION 1 8 3 2 5 4 6 7 9
